### ISSUE TITLE
Update mdast to remark

### ISSUE THREAD

**Issue by wooorm** [ben-eb/remark-midas#1]
(same as https://github.com/ben-eb/mdast-highlight.js/issues/3)

Hey! Just wanted ping and request a name change from mdast to remark.

You’ve probably already seen it but here’s a list of [tips for updating](https://github.com/wooorm/remark/blob/master/doc/plugins.md#renaming-from-mdast-to-remark). And here’s a list of reasons [why to update](https://github.com/wooorm/remark/releases/tag/3.0.0).

Let me know if I can help! :smile:

**Comment by ben-eb** [comment]
Done. https://github.com/ben-eb/remark-midas/commit/76d37fb000c798678d7835bdad3b3b98181547b1

**Comment by wooorm** [comment]
Thanks a lot, @ben-eb!

**Comment by ben-eb** [comment]
No problem. :+1:
